mysql: &mysql
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  pool: 10
  database: ensogo_production
  username:
  password:
  socket: /tmp/mysql.sock

development:
  <<: *mysql
  database: blog
  host: localhost
  username: root
  password:

test:
  <<: *mysql
  database: ensogo_test
  host: localhost
  username: root
  password:

production:
  <<: *mysql
